import React from 'react'
import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faInstagram, faLinkedin, faGithub } from '@fortawesome/free-brands-svg-icons'
import Lottie from "lottie-react";
import animationData from "../public/lap.json";

const Contact = () => {
    return (
        <>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <div className="container px-5 ">
                    <div className="row gx-5 align-items-center">
                        <div className="col-xxl-5">

                            <div className="text-center text-xxl-start">
                                <h1 className="display-3 fw-bolder mb-5"><span className={`${styles.textGradient} d-inline`}>Get in touch</span></h1>
                                <div className="fs-3  fw-bolder text-muted">Siddhant Sanjay Giri</div>
                                <div className="fs-3 fw-light text-muted">siddhantgiri97@gmail.com</div>
                                <div className="fs-3 fw-light text-muted">+91-7387086267</div>
                                <div className="fs-3 fw-light text-muted">Pune, Maharashtra</div>
                                <div className={`d-flex justify-content-center fs-2 gap-4 mt-5`}>
                                    <a href="https://www.instagram.com/siddhantgiri97/" target="_blank" id={styles.TextGr} ><FontAwesomeIcon icon={faInstagram} size="lg" /></a>
                                    <a id={styles.Gradient} href="https://github.com/Siddhantgiri97" target="_blank"><FontAwesomeIcon icon={faLinkedin} size='lg' /></a>
                                    <a id={styles.Gradient} href="https://www.linkedin.com/in/siddhant-giri-64042a208/" target="_blank"><FontAwesomeIcon icon={faGithub} size='lg' /></a>
                                </div>
                            </div>
                        </div>
                        <div className="col-xxl-7">
                            <div className="d-flex justify-content-center mt-5 mt-xxl-0">
                                <div className={`${styles.profile}`}>
                                    <Lottie
                                        animationData={animationData}
                                        className={styles.profieImg}
                                        loop={true}
                                        width="60vw"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Contact
