import Head from 'next/head'
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faInstagram, faLinkedin, faGithub } from '@fortawesome/free-brands-svg-icons'

import Lottie from "lottie-react";
import animationData from "../public/coder.json";


import styles from '@/styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className="d-flex flex-column h-100">
          <main className="flex-shrink-0">

            <header className="py-5">
              <div className="container px-5 pb-5">
                <div className="row gx-5 align-items-center">
                  <div className="col-xxl-5">

                    <div className="text-center text-xxl-start">
                      <div className={`badge ${styles.bgGradientPrimaryToSecondary} text-white mb-4`}><div className="text-uppercase">Design &middot; Development &middot; Deploy</div></div>
                      <div className="fs-3 fw-light text-muted">I can help your business to</div>
                      <h1 className="display-3 fw-bolder mb-5"><span className={`${styles.textGradient} d-inline`}>Get online and grow fast</span></h1>
                      <div className="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start mb-3">
                        <Link className="btn btn-primary btn-lg px-5 py-3 me-sm-3 fs-6 fw-bolder" href="/resume">Resume</Link>
                        <Link className="btn btn-outline-dark btn-lg px-5 py-3 fs-6 fw-bolder" href="/projects">Projects</Link>
                      </div>
                    </div>
                  </div>
                  <div className="col-xxl-7">
                    <div className="d-flex justify-content-center mt-5 mt-xxl-0">
                      <div className={`${styles.profile} ${styles.bgGradientPrimaryToSecondary}`}>
                        {/* <Image className={styles.profileImg} src={profile} alt="..." /> */}
                        <Lottie
                          animationData={animationData}
                          className={styles.profieImg}
                          loop={true}
                          width="50vw"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </header>

            <section className="bg-light py-5">
              <div className="container px-5">
                <div className="row gx-5 justify-content-center">
                  <div className="col-xxl-8">
                    <div className="text-center my-5">
                      <h2 className="display-5 fw-bolder"><span className={`${styles.textGradient} d-inline`}>About Me</span></h2>
                      <p className="lead fw-light mb-4">My name is Siddhant Giri and I help brands grow.</p>
                      <p className="text-muted">I&apos;m an accomplished engineering student with a passion for innovation and a strong background in computer science. Completed my Bachelor&apos;s degree at Pune Vidhyarthi Griha&apos;s College of Engineering and Technology, I am constantly seeking out new opportunities to challenge myself and expand my skillset. <br />I am passionate about using my skills and knowledge to drive innovation and make a positive impact in the world. I am excited to explore new opportunities and challenges in my career and would love to connect with other professionals who share this same drive and passion.</p>
                      <div className="d-flex justify-content-center fs-2 gap-4">
                        <a id={styles.Gradient} href="https://www.instagram.com/siddhantgiri97/" target="_blank"><FontAwesomeIcon icon={faInstagram} size="lg"  /></a>
                        <a id={styles.Gradient} href="https://www.linkedin.com/in/siddhant-giri-64042a208/" target="_blank"><FontAwesomeIcon icon={faLinkedin} size='lg' /></a>
                        <a id={styles.Gradient} href="https://github.com/Siddhantgiri97" target="_blank"><FontAwesomeIcon icon={faGithub} size='lg' /></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </main>
        </div>
      </main>
    </>
  )
}
