import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faGithub } from '@fortawesome/free-brands-svg-icons'
import { faArrowUpRightFromSquare } from '@fortawesome/free-solid-svg-icons'
import styles from '@/styles/Home.module.css'
import image1 from "../public/1.jpg"
import image2 from "../public/2.jpg"
import image3 from "../public/3.jpg"
import image4 from "../public/4.jpg"
import Link from 'next/link'

const Projects = () => {
    return (
        <>
            <Head>
                <title>Projects</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="d-flex flex-column h-100 bg-light">
                <main className="flex-shrink-0">

                    <section className="py-5">
                        <div className="container px-4 mb-5">
                            <div className="text-center mb-5">
                                <h1 className="display-5 fw-bolder mb-0"><span className={`${styles.textGradient} d-inline`}>Projects</span></h1>
                            </div>
                            <div className="row gx-5 justify-content-center">
                                <div className="col-lg-12 col-xl-9 col-xxl-8">

                                    <div className="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                        <div className="card-body p-0">
                                            <div className="d-flex align-items-center" id={styles.cardImg} >
                                                <div className="p-5">
                                                    <h2 className="fw-bolder">Countering Deep Fake Videos using Blockchain</h2>
                                                    <ul>
                                                        <li>Leveraged the transparency and immutability of blockchain technology to provide users with a reliable and decentralized verification mechanism for video content.</li>
                                                        <li>Utilized blockchain&apos;s timestamping capabilities to establish an auditable record of video authenticity, preventing
                                                            tampering or manipulation of video files.</li>
                                                        <li>Designed the application with scalability in mind, ensuring it can handle a growing user base and increasing
                                                            demand for deepfake detection and prevention.</li></ul>
                                                    <div className="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start my-3">
                                                        
                                                        <a className="btn btn-outline-dark btn-lg px-3 py-3 fs-6 fw-bolder" href="https://github.com/Siddhantgiri97/Video-Crate" target="_blank"><div className="d-inline-block me-2"><FontAwesomeIcon icon={faGithub} /></div>Source Code</a>
                                                    </div>
                                                </div>
                                                <Image className='img-fluid rounded-4' src={image1} alt="..." width={300} />
                                            </div>
                                        </div>

                                    </div>

                                    <div className="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                        <div className="card-body p-0">
                                            <div className="d-flex align-items-center" id={styles.cardImg}>
                                                <div className="p-5">
                                                    <h2 className="fw-bolder">Student Nexus </h2>
                                                    <ul>
                                                        <li>Spearheaded the development of a full-stack web application with robust authentication, enabling seamless profile
                                                            management for students and enhancing academic progress tracking.</li>
                                                        <li>Implemented a user-friendly dashboard granting notifications, personalized rank lists, and performance analytics.</li>
                                                        <li>Pioneered the creation of an interactive community platform, facilitating knowledge-sharing and doubt resolution
                                                            among students, resulting in promoting collaborative learning.</li></ul>
                                                    <div className="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start my-3">
                                                        
                                                        <a className="btn btn-outline-dark btn-lg px-3 py-3 fs-6 fw-bolder" href="https://github.com/Siddhantgiri97/Student-Nexus" target="_blank"><div className="d-inline-block me-2"><FontAwesomeIcon icon={faGithub} /></div>Source Code</a>
                                                    </div>
                                                </div>
                                                <Image className="img-fluid rounded-4" src={image2} alt="..." width={300} />
                                            </div>

                                        </div>
                                    </div>

                                    <div className="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                        <div className="card-body p-0">
                                            <div className="d-flex align-items-center" id={styles.cardImg}>
                                                <div className="p-5">
                                                    <h2 className="fw-bolder">Application Tracking System </h2>
                                                    <ul>
                                                        <li>The ATS system parses resume content into categories and then scans it for specific and relevant keywords.</li>
                                                        <li>Determines if the job application should be passed along to the recruiter.</li>
                                                        <li>Gained valuable experience in back-end development, data analytics, and information retrieval systems.</li></ul>
                                                    <div className="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start my-3">
                                                        
                                                        <a className="btn btn-outline-dark btn-lg px-3 py-3 fs-6 fw-bolder" href="https://github.com/Siddhantgiri97/ATS" target="_blank"><div className="d-inline-block me-2"><FontAwesomeIcon icon={faGithub} /></div>Source Code</a>
                                                    </div>
                                                </div>
                                                <Image className="img-fluid rounded-4" src={image3} alt="..." width={300} />
                                            </div>

                                        </div>
                                    </div>

                                    <div className="card overflow-hidden shadow rounded-4 border-0">
                                        <div className="card-body p-0">
                                            <div className="d-flex align-items-center" id={styles.cardImg}>
                                                <div className="p-5">
                                                    <h2 className="fw-bolder">Portfolio Management System </h2>
                                                    <ul>
                                                        <li> The system provides a central hub for tracking and overseeing stock investments. Users can quickly review their current stock holdings in one place.</li>
                                                        <li> With just a few clicks, users can buy and sell stocks, thanks to a straightforward interface. They can make informed decisions using real-time stock prices.</li>
                                                        <li>Users can evaluate their portfolio&apos;s performance, gaining insights into gains, losses, and overall trends. Visualizations are available for a clear understanding.</li></ul>
                                                    <div className="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xxl-start my-3">
                                                        
                                                        <a className="btn btn-outline-dark btn-lg px-3 py-3 fs-6 fw-bolder" href="https://github.com/Siddhantgiri97/Portfolio-Management-System" target="_blank"><div className="d-inline-block me-2"><FontAwesomeIcon icon={faGithub} /></div>Source Code</a>
                                                    </div>
                                                </div>
                                                <Image className="img-fluid rounded-4" src={image4} alt="..." width={300} />
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    <section className={`py-5 ${styles.bgGradientPrimaryToSecondary} text-white`}>
                        <div className="container px-5 my-5">
                            <div className="text-center">
                                <h2 className="display-4 fw-bolder mb-4">Let&apos;s build something together</h2>
                                <Link className="btn btn-outline-light btn-lg px-5 py-3 fs-6 fw-bolder" href="/contact">Contact me</Link>
                            </div>
                        </div>
                    </section>
                </main>

            </div>
        </>
    )
}

export default Projects