import React from 'react'
import Head from 'next/head'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faDownload, faCode, faLaptopCode } from '@fortawesome/free-solid-svg-icons'
import styles from '@/styles/Home.module.css'


const handleDownload = () => {
    window.location.href = "./Siddhant_Giri_Resume.pdf"
    window.location.download = "Siddhant_Giri"
}

const Resume = () => {
    return (<>
        <Head>
            <title>Resume</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="d-flex flex-column h-100 bg-light">
            <main className="flex-shrink-0">

                <div className="container px-3 my-5">
                    <div className="text-center mb-5">
                        <h1 className="display-5 fw-bolder mb-0"><span className={`${styles.textGradient} d-inline`}>Resume</span></h1>
                    </div>
                    <div className="row gx-5 justify-content-center">
                        <div className="col-lg-12 col-xl-9 col-xxl-8">

                            <section>
                                <div className="d-flex align-items-center justify-content-between mb-5" id={styles.btTxt}>
                                    <h2 className="text-primary fw-bolder mb-0">Experience</h2>

                                    <a className="btn btn-primary px-4 py-3" onClick={handleDownload}>
                                        <div className="d-inline-block me-2"><FontAwesomeIcon icon={faDownload} beat size="lg" /></div>
                                        Download Resume
                                    </a>
                                </div>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className="text-primary fw-bolder mb-2">May 2022 - Jun 2022</div>
                                                    <div className="small fw-bolder">Martian Program Intern</div>
                                                    <div className="small text-muted">Persistent Systems</div>
                                                    <div className="small text-muted">Pune, MH</div>
                                                </div>
                                            </div>
                                            <div className="col-lg-7" style={{textAlign:"justify"}}><div>
                                                <ul>
                                                    
                                                    <li>Strengthened the foundation and demonstrated proficiency in computer fundamentals, scoring an average of 90%
                                                        in technical assessments.
                                                    </li>
                                                    <li>Embraced a culture of continuous learning and improvement, fostering personal and professional growth.</li>
                                                </ul>
                                            </div></div>
                                        </div>
                                    </div>
                                </div>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className="text-primary fw-bolder mb-2">Mar 2021 - Jun 2021</div>
                                                    <div className="small fw-bolder">Full Stack Developer</div>
                                                    <div className="small text-muted">Origin Institute</div>
                                                    <div className="small text-muted">Akola, MH</div>
                                                </div>
                                            </div>
                                            <div className="col-lg-7" style={{textAlign:"justify"}}><div><ul>
                                                <li>Collaborated with a cross-functional team of designers and stakeholders to deliver multiple features.</li>
                                                <li>Developed an interactive website that ensured a 65% increase in website traffic and a 40% boost in page views.
                                                </li>
                                                
                                            </ul></div></div>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            <section>
                                <h2 className=" fw-bolder mb-4" id={styles.pinkText} >Education</h2>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className=" fw-bolder mb-2" id={styles.pinkText}>Aug 2019 - Jul 2023</div>
                                                    <div className="mb-2">
                                                        <div className="small fw-bolder">PVG&apos;s COET</div>
                                                        <div className="small text-muted">Pune, MH</div>
                                                    </div>
                                                    <div className="fst-italic">
                                                        <div className="small text-muted">Information Technology</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-7" style={{textAlign:"justify"}}><div> <ul>
                                                <li>Aggregate CGPA: 9.34</li>
                                                <li>I honed my ability to adapt to ever-evolving technology trends and developed strong problem-solving capabilities, making me an effective problem solver in the IT field.</li></ul> </div></div>
                                        </div>
                                    </div>
                                </div>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className=" fw-bolder mb-2" id={styles.pinkText}>Jun 2016 - Jun 2018</div>
                                                    <div className="mb-2">
                                                        <div className="small fw-bolder">Shri. R. L. T college of science</div>
                                                        <div className="small text-muted">Akola, MH</div>
                                                    </div>
                                                    <div className="fst-italic">
                                                        <div className="small text-muted">Higher Secondary</div>
                                                        <div className="small text-muted">Computer Science</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-7" style={{textAlign:"justify"}}><div><ul>
                                                <li>Class XII Percentage: 73.85 % </li>
                                                <li>My higher secondary certificate in computer science provided me with a strong foundation in key computer science concepts, setting the stage for effective learning and application in the field.</li></ul> </div></div>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            <div className="pb-5"></div>

                            <section>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">

                                        <div className="mb-5">
                                            <div className="d-flex align-items-center mb-4">
                                                <div className={`${styles.feature} bg-primary ${styles.bgGradientPrimaryToSecondary} text-white rounded-3 me-3`}><FontAwesomeIcon icon={faLaptopCode} /></div>
                                                <h3 className="fw-bolder mb-0"><span className={`${styles.textGradient} d-inline`}>Professional Skills</span></h3>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3 mb-4">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Web Development</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Software Development</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Blockchain</div></div>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3 mb-4">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Network Security</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Operating System</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Web Design</div></div>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3 mb-4">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Machine Learning</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Computer Vision</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">MongoDB</div></div>
                                            </div>
                                        </div>

                                        <div className="mb-0">
                                            <div className="d-flex align-items-center mb-4">
                                                <div className={`${styles.feature} bg-primary ${styles.bgGradientPrimaryToSecondary} text-white rounded-3 me-3`}><FontAwesomeIcon icon={faCode} /></div>
                                                <h3 className="fw-bolder mb-0"><span className={`${styles.textGradient} d-inline`}>Programming Languages</span></h3>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3 mb-4">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">C++</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Java</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Solidity</div></div>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3 mb-4">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">HTML</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">CSS</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">JavaScript</div></div>
                                            </div>
                                            <div className="row row-cols-1 row-cols-md-3">
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">Django</div></div>
                                                <div className="col mb-4 mb-md-0"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">MySQL</div></div>
                                                <div className="col"><div className="d-flex align-items-center bg-light rounded-4 p-3 h-100">React JS</div></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            <section>
                                <h2 className=" fw-bolder mb-4" id={styles.pinkText} >Certification</h2>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-4">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className=" fw-bolder mb-2" id={styles.pinkText}>September 2021</div>
                                                    <div className="mb-2">
                                                        <div className="small fw-bolder">AI Masterclass with Python</div>
                                                        <div className="small text-muted">Pantech Solutions</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-4">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className=" fw-bolder mb-2" id={styles.pinkText}>December 2020</div>
                                                    <div className="mb-2">
                                                        <div className="small fw-bolder">Java, Python</div>
                                                        <div className="small text-muted">IIT Bombay</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>

                            <section>
                                <h2 className="text-primary fw-bolder mb-4" >Publication</h2>

                                <div className="card shadow border-0 rounded-4 mb-5">
                                    <div className="card-body p-5">
                                        <div className="row align-items-center gx-5">
                                            <div className="col text-center text-lg-start mb-4 mb-lg-0">
                                                <div className="bg-light p-4 rounded-4">
                                                    <div className="text-primary fw-bolder mb-2">September 2021</div>
                                                    <div className="mb-2">
                                                        <div className="small fw-bolder">Countering Deep Fake Videos using Blockchain</div>
                                                        <div className="small text-muted">TIJER-International Research Journal (TIJER)</div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-lg-7" style={{textAlign:"justify"}}><div>Explored the underlying principles of blockchain technology and its immutable, decentralized nature,
                                                highlighting its potential for ensuring trust and authenticity in digital media.</div></div>
                                        </div>
                                    </div>
                                </div>

                            </section>
                        </div>
                    </div>
                </div>
            </main>



        </div>
    </>
    )
}

export default Resume